name: Auto Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH and restart Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/root/mandilink || git clone https://github.com/mandilinkybl-pixel/Mandilink.git /home/root/mandilink
            cd /home/root/mandilink
            git pull origin main
            docker-compose build
            docker-compose up -d
